sudo: false
os: linux
install:
  - | # setup ~/.local/bin
    mkdir -p ~/.local/bin;
    export PATH=$HOME/.local/bin:$PATH;
  - | # download shellcheck
    shellcheck_tarball="shellcheck-stable.linux.x86_64.tar.xz";
    wget "https://storage.googleapis.com/shellcheck/${shellcheck_tarball}";
    tar --xz -xvf "${shellcheck_tarball}";
    mv shellcheck-stable/shellcheck ~/.local/bin/shellcheck;
    rm -r shellcheck-stable;
    rm "${shellcheck_tarball}";
script:
  - make test
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
